name: Test and Release

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pre-commit==2.6.0
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 .
    - name: pre-commit hooks
      run: pre-commit run --all-files
    - name: Run tests
      run: nosetests -v --rednose --nologcapture --nocapture tests
